language: objective-c
osx_image: xcode8.3
cache: cocoapods
podfile: Example/Podfile
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
- bundle install
install:
- bundle exec pod repo update
- bundle exec pod install --project-directory=Example
script: ./travis-build.sh
