language: objective-c
osx_image: xcode8.2
cache: cocoapods
podfile: Example/Podfile
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
- gem install cocoapods -v 1.2.0
- pod repo update
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script: ./travis-build.sh
