language: objective-c
osx_image: xcode8
cache: cocoapods
podfile: Example/Podfile
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/IRLSizeExample.xcworkspace
  - IOS_SDK=iphonesimulator9.2
  - EXAMPLE_SCHEME="IRLSizeExample"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7"             POD_LINT="NO"
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"        POD_LINT="NO"
    - DESTINATION="OS=10.0,name=iPad Pro (9.7 inch)"  POD_LINT="NO"
    - DESTINATION="OS=10.0,name=iPad Pro (12.9 inch)" POD_LINT="NO"
    - DESTINATION="OS=10.0,name=iPhone SE"            POD_LINT="YES"
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcrun simctl list

  - xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug test | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
